version: 2.1

jobs:
 build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
  build2:
     docker:
      - image: circleci/ruby:2.4-node
      steps:
       - checkout
      
workflows:
  version: 2.1
  
  my_workflow:
     jobs:
        - build
        - build2
           requires:
             - build
